# -*- coding: utf-8 -*-
"""
三岗位知识库：技能图谱、匹配关键词、学习资源与面试问题。

维度说明：
- 核心技能：岗位硬技能
- 项目经验：是否有相关落地 / 项目经历
- 教育背景：专业 / 学历相关性
- 综合素养：软技能

importance: 1(锦上添花) ~ 5(必备)。匹配度按权重汇总；差距按 importance 排序。

历次更新：
- 2026-07-30 扩充三岗位关键词库：每个 skill 增加更多同义/相关匹配词，
  并新增 AI 原生产品设计、Agent 产品认知、AI PM 方法论、AI 伦理合规、
  评估与可观测、多模态、AI 安全护栏、AI 搜索/SEO、电商直播运营、用户分层/CRM 等技能。
- 2026-07-30 v2 每个 skill 补充大量英文关键词等价物，支持英文 JD / 英文简历匹配。
"""

DIMENSIONS = ["核心技能", "项目经验", "教育背景", "综合素养"]

# 通用学习资源兜底（中英文双语兜底域名）
GENERIC_RESOURCE = {"name": "在 B 站 / 掘金搜索对应关键词", "url": "https://search.bilibili.com/all?keyword="}
EN_RESOURCE = {"name": "Search Google / YouTube for keywords", "url": "https://www.google.com/search?q="}

ROLES = {
    "ai_product": {
        "label": "AI 产品",
        "desc": "面向 AI 产品的需求洞察、LLM 应用认知与 0-1 落地能力。",
        "skills": [
            # 核心技能
            {"id": "ap_req", "label": "需求分析", "dim": "核心技能", "importance": 5,
             "keywords": ["需求分析", "需求调研", "requirement", "用户痛点", "场景梳理", "产品规划",
                          "需求池", "用户故事", "验收标准", "use case", "用例", "痛点分析", "场景挖掘",
                          "requirement analysis", "requirement gathering", "user story", "acceptance criteria",
                          "product roadmap", "feature prioritization", "stakeholder", "use case analysis",
                          "market requirement", "mrd", "prd", "backlog", "pain point", "user scenario"],
             "learn": "练习把模糊诉求拆成可验证的用户故事与验收标准，建立 MRD/PRD 思维。",
             "resource": {"name": "《启示录》+ 人人都是产品经理", "url": "https://www.woshipm.com"}},
            {"id": "ap_user", "label": "用户研究", "dim": "核心技能", "importance": 4,
             "keywords": ["用户研究", "用户访谈", "user research", "调研", "用户画像", "问卷",
                          "旅程地图", "jtbd", "jobs to be done", "可用性测试", "焦点小组", "focus group", "persona", "用户分层",
                          "user interview", "survey", "usability testing", "user profile", "customer journey",
                          "qualitative research", "quantitative research", "user need", "user persona",
                          "user experience research", "ux research", "focus group", "customer insight"],
             "learn": "掌握访谈提纲设计、定性+定量结合的研究方法，建立用户同理心。",
             "resource": {"name": " Nielsen Norman Group", "url": "https://www.nngroup.com"}},
            {"id": "ap_prd", "label": "PRD 撰写", "dim": "核心技能", "importance": 4,
             "keywords": ["prd", "产品需求文档", "需求文档", "产品文档", "产品规划",
                          "roadmap", "功能列表", "交互说明", "需求评审", "功能设计", "规格说明",
                          "product requirements document", "specification", "feature list",
                          "requirements document", "product spec", "functional spec", "technical writing",
                          "product documentation", "requirement review", "feature design"],
             "learn": "用结构化模板写 PRD：背景、目标、范围、功能列表、交互、数据埋点。",
             "resource": {"name": "腾讯 CDC PRD 模板", "url": "https://cdc.tencent.com"}},
            {"id": "ap_proto", "label": "产品原型", "dim": "核心技能", "importance": 3,
             "keywords": ["原型", "axure", "figma", "墨刀", "线框图", "wireframe", "交互设计",
                          "原型设计", "可点击原型", "ux", "用户体验", "交互稿", "ui",
                          "prototype", "interaction design", "mockup", "clickable prototype",
                          "ui design", "user interface", "ux design", "product prototype",
                          "interactive prototype", "low fidelity", "high fidelity"],
             "learn": "熟练 Figma 画出可点击原型，能和技术对齐交互细节。",
             "resource": {"name": "Figma 官方教程", "url": "https://www.figma.com/resources/learn-design/"}},
            {"id": "ap_data", "label": "数据分析", "dim": "核心技能", "importance": 4,
             "keywords": ["数据分析", "data analysis", "埋点", "指标", "ab测试", "a/b", "留存", "转化",
                          "sql", "dashboard", "数据看板", "漏斗", "dau", "mau", "北极星", "留存率", "神策", "growth", "数据驱动",
                          "analytics", "metric", "kpi", "conversion", "retention", "funnel analysis",
                          "data driven", "data dashboard", "north star metric", "cohort analysis",
                          "product analytics", "user behavior", "event tracking"],
             "learn": "会用 SQL/神策/GA 看核心指标，用数据驱动迭代决策。",
             "resource": {"name": "SQL 菜鸟教程", "url": "https://www.runoob.com/sql/sql-tutorial.html"}},
            {"id": "ap_ab", "label": "A/B 测试", "dim": "核心技能", "importance": 2,
             "keywords": ["a/b", "ab测试", "ab experiment", "灰度", "实验",
                          "实验设计", "显著性", "对照组", "样本量", "假设检验",
                          "ab test", "a/b test", "experiment design", "hypothesis testing",
                          "statistical significance", "control group", "sample size",
                          "split test", "randomized experiment", "multivariate"],
             "learn": "理解实验设计的基本统计原理（显著性、样本量）。",
             "resource": {"name": "Evan Miller 在线工具", "url": "https://www.evanmiller.org/ab-testing/"}},
            {"id": "ap_comp", "label": "竞品分析", "dim": "核心技能", "importance": 3,
             "keywords": ["竞品", "competitive", "对标", "benchmark",
                          "swot", "差异化", "对标分析", "赛道", "竞争分析",
                          "competitor analysis", "competitive analysis", "market analysis",
                          "differentiation", "competitive landscape", "market research",
                          "positioning", "market intelligence"],
             "learn": "建立竞品矩阵分析法（功能/体验/商业模式三维度）。",
             "resource": {"name": "在 36氪 / 晚点搜索赛道", "url": "https://36kr.com"}},
            {"id": "ap_ml", "label": "机器学习基础", "dim": "核心技能", "importance": 3,
             "keywords": ["机器学习", "深度学习", "ml", "神经网络", "模型", "算法",
                          "transformer", "分类", "聚类", "推荐", "nlp", "cv", "监督学习", "无监督",
                          "machine learning", "deep learning", "neural network", "algorithm",
                          "supervised learning", "unsupervised learning", "classification",
                          "clustering", "recommender system", "regression", "model training",
                          "feature engineering", "nlp", "computer vision"],
             "learn": "理解监督/无监督、训练/推理、常见模型能力边界，能和算法同学对话。",
             "resource": {"name": "吴恩达 ML 专项", "url": "https://www.coursera.org/specializations/machine-learning-introduction"}},
            {"id": "ap_llm", "label": "LLM 应用认知", "dim": "核心技能", "importance": 5,
             "keywords": ["大模型", "llm", "gpt", "大语言模型", "aigc", "生成式", "prompt", "提示词",
                          "ai原生", "ai-native", "agent产品", "chatbot", "copilot", "多模态", "aigc应用", "ai workflow", "生成式ai",
                          "large language model", "generative ai", "genai", "prompt engineering",
                          "ai native", "ai agent product", "conversational ai", "rag", "fine tuning",
                          "ai application", "llm application", "foundation model", "gpt-4"],
             "learn": "亲自用过主流大模型与 Agent 产品，理解 RAG/Agent/微调的适用边界与产品形态。",
             "resource": {"name": "OpenAI 官方 Cookbook", "url": "https://cookbook.openai.com"}},
            {"id": "ap_biz", "label": "商业化思维", "dim": "核心技能", "importance": 3,
             "keywords": ["商业化", "变现", "营收", "商业", "收费", "订阅", "定价",
                          "ltv", "arpu", "saas", "订阅制", "付费", "pmf", "单位经济", "盈利模式",
                          "monetization", "business model", "revenue", "pricing", "subscription",
                          "unit economics", "profitability", "go to market", "business strategy",
                          "customer acquisition cost", "cac", "lifetime value", "saas metrics"],
             "learn": "能设计定价/增长模型，理解 PMF 与单位经济。",
             "resource": {"name": "《增长黑客》", "url": "https://book.douban.com"}},
            {"id": "ap_ainative", "label": "AI 原生产品设计", "dim": "核心技能", "importance": 5,
             "keywords": ["ai原生设计", "ai-first", "人机协作", "ai交互", "conversational ui", "对话式交互",
                          "ai workflow", "copilot设计", "生成式交互", "ai产品设计", "ai产品形态",
                          "ai-native design", "human-ai collaboration", "generative interaction",
                          "ai-first product", "conversational interface", "ai interaction",
                          "copilot design", "ai product design", "intent driven"],
             "learn": "理解 AI 原生应用与传统软件的本质差异：从「用户操作」到「用户描述意图、AI 执行」，设计人机协作闭环。",
             "resource": {"name": "OpenAI 产品设计指南", "url": "https://platform.openai.com/docs/guides/product"}},
            {"id": "ap_agent_prod", "label": "Agent 产品认知", "dim": "核心技能", "importance": 4,
             "keywords": ["agent产品", "工作流自动化", "多智能体产品", "ai agent", "任务编排",
                          "工具调用产品", "智能体产品", "自动化产品", "ai工作流",
                          "agent product", "workflow automation", "multi-agent product",
                          "task orchestration", "tool calling", "ai agent product",
                          "autonomous agent", "agentic workflow", "ai automation"],
             "learn": "理解 Agent 能解决什么、不能解决什么，能把业务流程拆成「可自主执行的任务 + 人工确认节点」。",
             "resource": {"name": "Anthropic 构建 Agent 指南", "url": "https://www.anthropic.com/engineering/building-effective-agents"}},
            {"id": "ap_aipm", "label": "AI PM 方法论", "dim": "核心技能", "importance": 4,
             "keywords": ["ai pm", "ai产品方法论", "llm产品", "生成式ai产品", "ai需求",
                          "大模型产品", "ai产品 manager", "genai product",
                          "ai product management", "ai product manager", "llm product management",
                          "generative ai product", "ai product strategy", "model evaluation"],
             "learn": "建立 AI 产品特有的方法论：模型能力评估、效果兜底、成本控制、安全边界设计。",
             "resource": {"name": "Lenny's Podcast (AI PM)", "url": "https://www.lennysnewsletter.com"}},
            {"id": "ap_ethics", "label": "AI 伦理与合规", "dim": "核心技能", "importance": 2,
             "keywords": ["合规", "隐私", "数据安全", "内容安全", "版权", "伦理", "监管",
                          "个人信息保护", "ai治理", "备案", "审核",
                          "compliance", "privacy", "data security", "content safety", "copyright",
                          "ai ethics", "regulation", "ai governance", "responsible ai",
                          "data protection", "gdpr", "content moderation", "ai safety"],
             "learn": "了解生成式 AI 的合规红线（内容安全、版权、个人信息保护），能在产品设计中预埋护栏。",
             "resource": {"name": "网信办生成式AI 服务管理办法", "url": "https://www.cac.gov.cn"}},
            {"id": "ap_growth", "label": "产品增长", "dim": "核心技能", "importance": 3,
             "keywords": ["增长", "增长策略", "病毒", "裂变", "留存", "激活",
                          "growth hacking", "拉新", "aarrr", "海盗模型", "推荐机制",
                          "growth", "growth strategy", "viral", "referral", "retention", "activation",
                          "user acquisition", "aarrr funnel", "product growth", "growth hacking",
                          "recommendation system", "organic growth", "paid acquisition"],
             "learn": "理解 AARRR 增长漏斗，能结合产品特性设计激活与留存机制。",
             "resource": {"name": "《增长黑客》", "url": "https://book.douban.com"}},

            # 项目经验
            {"id": "ap_01", "label": "0-1 产品经验", "dim": "项目经验", "importance": 4,
             "keywords": ["从0到1", "0到1", "0-1", "孵化", "mvp", "立项", "搭建产品",
                          "产品孵化", "incubate", "从想法到上线", "产品从0到1",
                          "0 to 1", "product incubation", "minimum viable product",
                          "product launch", "idea to product", "new product development",
                          "product inception", "greenfield"],
             "learn": "争取独立负责一个小功能或副业项目的从 0 到 1，沉淀复盘文档。",
             "resource": {"name": "做 1 个 AI 小工具并上线", "url": "https://vercel.com"}},
            {"id": "ap_ship", "label": "AI 产品落地", "dim": "项目经验", "importance": 4,
             "keywords": ["落地", "上线", "交付", "发布", "迭代", "上线运营",
                          "灰度发布", "数据复盘", "上线后", "abtest", "全量",
                          "product launch", "delivery", "release", "iteration", "go live",
                          "product ship", "deployment", "production", "product delivery",
                          "post launch", "full rollout", "canary release"],
             "learn": "跑通过需求→开发→灰度→上线的完整闭环，准备项目复盘稿。",
             "resource": GENERIC_RESOURCE},
            {"id": "ap_cross", "label": "跨团队协作", "dim": "项目经验", "importance": 3,
             "keywords": ["跨团队", "协作", "协调", "推动", "对齐", "项目管理",
                          "okr", "协同", "跨部门", "推动落地",
                          "cross team", "collaboration", "coordination", "stakeholder management",
                          "cross functional", "alignment", "teamwork", "cross department",
                          "okr", "project coordination"],
             "learn": "练习用 OKR/周会机制推动设计、研发、算法协同。",
             "resource": GENERIC_RESOURCE},
            {"id": "ap_pm", "label": "项目管理", "dim": "项目经验", "importance": 3,
             "keywords": ["项目管理", "pmp", "排期", "迭代", "敏捷", "scrum",
                          "甘特图", "风险管理", "需求管理", "里程碑",
                          "project management", "agile", "scrum", "sprint", "milestone",
                          "risk management", "gantt chart", "resource planning",
                          "project planning", "delivery management", "kanban"],
             "learn": "掌握看板/里程碑管理，能控进度与风险。",
             "resource": {"name": " Atlassian 项目管理指南", "url": "https://www.atlassian.com/agile"}},

            # 教育背景
            {"id": "ap_edu", "label": "计算机/相关专业", "dim": "教育背景", "importance": 2,
             "keywords": ["计算机", "软件", "信息", "数据科学", "人工智能", "产品", "统计", "数学",
                          "交互设计", "hci", "人机交互", "商科", "管理",
                          "computer science", "software engineering", "data science", "ai",
                          "information systems", "statistics", "mathematics", "hci",
                          "human computer interaction", "business", "management",
                          "interaction design", "information technology"],
             "learn": "若非相关背景，可补 1 门产品/数据分析入门课增强说服力。",
             "resource": GENERIC_RESOURCE},
            {"id": "ap_deg", "label": "学历背景", "dim": "教育背景", "importance": 1,
             "keywords": ["本科", "硕士", "博士", "bachelor", "master", "985", "211",
                          "bachelor", "master", "phd", "undergraduate", "graduate",
                          "bachelors degree", "masters degree", "doctorate"],
             "learn": "学历为加分项，重点仍应放在项目与作品集。",
             "resource": GENERIC_RESOURCE},

            # 综合素养
            {"id": "ap_comm", "label": "沟通表达", "dim": "综合素养", "importance": 3,
             "keywords": ["沟通", "表达", "汇报", "演讲", "ppt", "presentation",
                          "storytelling", "讲故事", "说服",
                          "communication", "presentation", "public speaking", "storytelling",
                          "verbal communication", "written communication", "reporting",
                          "stakeholder communication", "team communication"],
             "learn": "练习结构化表达（结论先行），沉淀 1 份产品汇报 PPT。",
             "resource": GENERIC_RESOURCE},
            {"id": "ap_logic", "label": "逻辑思维", "dim": "综合素养", "importance": 3,
             "keywords": ["逻辑", "结构化", "复盘", "分析",
                          "mece", "金字塔", "第一性原理", "批判性",
                          "logical thinking", "structured thinking", "critical thinking",
                          "first principles", "problem solving", "analytical",
                          "strategic thinking", "framework", "mece principle"],
             "learn": "用 MECE / 金字塔原理组织分析与汇报。",
             "resource": {"name": "《金字塔原理》", "url": "https://book.douban.com"}},
            {"id": "ap_learn", "label": "快速学习", "dim": "综合素养", "importance": 2,
             "keywords": ["自学", "快速学习", "自我驱动", "学习能力强",
                          "好奇心", "信息检索", "主动学习",
                          "self learning", "fast learner", "self motivated", "curiosity",
                          "quick learner", "self driven", "continuous learning",
                          "independent learning", "information retrieval"],
             "learn": "建立知识管理习惯（笔记/卡片盒），持续追踪 AI 新动态。",
             "resource": GENERIC_RESOURCE},
        ],
        "interview_base": [
            "请用 3 分钟介绍你最满意的一个产品项目，以及你在其中承担的角色。",
            "如果让你从 0 到 1 设计一款面向大学生的 AI 学习助手，你会怎么切入？",
            "你如何判断一个 AI 功能该用 RAG 还是微调？请结合产品目标说明。",
            "请举一个你用数据驱动产品迭代的例子。",
            "如果一个 AI 功能的准确率只有 80%，你会如何在产品设计上兜底以保证用户体验？",
        ],
    },

    "ai_agent": {
        "label": "AI Agent 开发",
        "desc": "面向 LLM / Agent 的工程实现能力：RAG、MCP、多智能体与工程落地。",
        "skills": [
            # 核心技能
            {"id": "aa_py", "label": "Python", "dim": "核心技能", "importance": 5,
             "keywords": ["python", "py", "pandas", "numpy",
                          "asyncio", "类型注解", "pytest", "poetry", "uv", "装饰器", "并发", "虚拟环境",
                          "python programming", "python development", "python backend",
                          "type hints", "async", "concurrency", "venv", "pip",
                          "package management", "python testing"],
             "learn": "扎实的 Python 基础（异步、类型注解、虚拟环境、包管理）。",
             "resource": {"name": "Python 官方教程", "url": "https://docs.python.org/zh-cn/3/tutorial/"}},
            {"id": "aa_js", "label": "前端/TS 基础", "dim": "核心技能", "importance": 2,
             "keywords": ["javascript", "typescript", "js", "ts", "node", "前端",
                          "next.js", "react", "tailwind", "vue",
                          "frontend", "node.js", "web development", "frontend development"],
             "learn": "能用 TS 写简单前端或后端，便于做 Agent 的可视化与联调。",
             "resource": {"name": "TypeScript 官方手册", "url": "https://www.typescriptlang.org/docs/"}},
            {"id": "aa_lc", "label": "LangChain/LangGraph", "dim": "核心技能", "importance": 4,
             "keywords": ["langchain", "langgraph", "langchain.js",
                          "llamaindex", "haystack", "semantic kernel", "crewai", "dify",
                          "langchain", "langgraph", "langchain framework",
                          "llamaindex", "ai orchestration", "agent framework"],
             "learn": "用 LangGraph 编排有状态的多步 Agent 工作流。",
             "resource": {"name": "LangChain 文档", "url": "https://python.langchain.com/docs/introduction/"}},
            {"id": "aa_rag", "label": "RAG 检索增强", "dim": "核心技能", "importance": 5,
             "keywords": ["rag", "检索增强", "向量检索", "知识库问答", "embedding",
                          "rerank", "重排", "混合检索", "hybrid", "graphrag", "知识图谱", "召回", "chunk", "切分", "ragas", "rag评估",
                          "retrieval augmented generation", "vector search", "embedding",
                          "rerank", "hybrid search", "knowledge graph", "chunking",
                          "retrieval", "semantic search", "dense retrieval", "sparse retrieval"],
             "learn": "掌握切分/向量化/重排/引用溯源的完整 RAG 链路与评测。",
             "resource": {"name": "LangChain RAG 教程", "url": "https://python.langchain.com/docs/tutorials/rag/"}},
            {"id": "aa_mcp", "label": "MCP 协议", "dim": "核心技能", "importance": 4,
             "keywords": ["mcp", "model context protocol", "工具调用", "function calling",
                          "tool use", "tool calling", "mcp server", "mcp client", "工具服务", "协议", "agent tools",
                          "model context protocol", "function calling", "tool use",
                          "mcp protocol", "tool service", "agent tool", "mcp server", "mcp client"],
             "learn": "理解 MCP 客户端/服务端模型，能为 Agent 封装工具服务。",
             "resource": {"name": "MCP 官方规范", "url": "https://modelcontextprotocol.io"}},
            {"id": "aa_api", "label": "大模型 API", "dim": "核心技能", "importance": 5,
             "keywords": ["claude api", "openai api", "gpt api", "大模型api", "api调用", "anthropic", "智谱", "通义", "kimi",
                          "gemini", "deepseek", "ollama", "本地模型", "流式", "streaming", "temperature", "token", "function call",
                          "llm api", "openai", "claude", "anthropic", "gemini", "deepseek",
                          "api integration", "streaming", "ollama", "local model",
                          "api call", "model endpoint", "inference api"],
             "learn": "熟练调用主流大模型 API，掌握流式输出、重试、降级与成本控制。",
             "resource": {"name": "OpenAI API 文档", "url": "https://platform.openai.com/docs"}},
            {"id": "aa_vec", "label": "向量数据库", "dim": "核心技能", "importance": 4,
             "keywords": ["向量数据库", "vector", "faiss", "milvus", "chroma", "pgvector", "qdrant",
                          "weaviate", "redis", "elasticsearch", "相似度", "ann",
                          "vector database", "vector store", "faiss", "milvus", "chroma",
                          "pgvector", "qdrant", "weaviate", "similarity search",
                          "approximate nearest neighbor", "indexing", "vector index"],
             "learn": "选型并落地一种向量库，理解索引与相似度度量。",
             "resource": {"name": "Chroma 文档", "url": "https://docs.trychroma.com"}},
            {"id": "aa_prompt", "label": "提示工程", "dim": "核心技能", "importance": 4,
             "keywords": ["提示工程", "prompt", "提示词", "few-shot", "chain-of-thought", "cot",
                          "system prompt", "系统提示", "结构化输出", "json mode", "输出解析", "约束", "角色设定",
                          "prompt engineering", "few shot", "chain of thought", "system prompt",
                          "structured output", "json mode", "output parsing", "role setting",
                          "prompt design", "instruction tuning", "zero shot"],
             "learn": "掌握角色/约束/示例/思维链等提示技巧与系统提示设计。",
             "resource": {"name": "Prompt Engineering Guide", "url": "https://www.promptingguide.ai/zh"}},
            {"id": "aa_agent", "label": "Agent 架构", "dim": "核心技能", "importance": 5,
             "keywords": ["agent", "智能体", "多智能体", "multi-agent", "自主", "规划", "反思",
                          "planning", "反思", "react", "memory", "长期记忆", "上下文", "orchestration", "编排", "toolformer", "任务分解",
                          "agent architecture", "multi-agent", "autonomous agent", "planning",
                          "reflection", "memory system", "orchestration", "task decomposition",
                          "toolformer", "agentic", "react loop", "agent workflow"],
             "learn": "理解规划-执行-反思循环，能设计单/多 Agent 协作架构。",
             "resource": {"name": "AutoGen 文档", "url": "https://microsoft.github.io/autogen/"}},
            {"id": "aa_backend", "label": "后端开发", "dim": "核心技能", "importance": 4,
             "keywords": ["后端", "fastapi", "flask", "django", "微服务", "api", "restful",
                          "redis", "celery", "websocket", "grpc", "postgresql", "mysql", "rest",
                          "backend", "backend development", "microservice", "rest api",
                          "api design", "database", "postgresql", "mysql", "redis",
                          "message queue", "celery", "websocket", "grpc", "server side"],
             "learn": "用 FastAPI 构建稳定的 Agent 服务与 API。",
             "resource": {"name": "FastAPI 文档", "url": "https://fastapi.tiangolo.com/zh/"}},
            {"id": "aa_fe", "label": "前端基础", "dim": "核心技能", "importance": 2,
             "keywords": ["前端", "vue", "react", "html", "css",
                          "tailwind", "组件", "typescript",
                          "frontend", "frontend development", "html", "css", "javascript",
                          "vue", "react", "tailwind css", "component", "web ui"],
             "learn": "能用 Vue/React 做简单交互页，便于联调 Agent 界面。",
             "resource": {"name": "Vue 官方教程", "url": "https://cn.vuejs.org/guide/introduction.html"}},
            {"id": "aa_ft", "label": "模型微调", "dim": "核心技能", "importance": 3,
             "keywords": ["微调", "fine-tune", "finetuning", "lora", "sft", "peft",
                          "rlhf", "dpo", "蒸馏", "embedding模型", "量化训练",
                          "fine tuning", "finetuning", "lora", "sft", "peft",
                          "rlhf", "dpo", "model distillation", "quantization",
                          "parameter efficient", "model training", "transfer learning"],
             "learn": "理解 SFT/LoRA 流程与适用场景，知道何时该微调而非提示。",
             "resource": {"name": "HuggingFace PEFT", "url": "https://huggingface.co/docs/peft"}},
            {"id": "aa_deploy", "label": "部署/推理优化", "dim": "核心技能", "importance": 3,
             "keywords": ["部署", "docker", "k8s", "推理", "inference", "性能优化", "量化", "vllm",
                          "serverless", "lambda", "gpu", "triton", "onnx", "tensorrt", "推理加速", "容器化",
                          "deployment", "docker", "kubernetes", "inference optimization",
                          "model serving", "vllm", "triton", "onnx", "tensorrt",
                          "gpu optimization", "serverless", "containerization",
                          "model deployment", "quantization"],
             "learn": "会用 Docker 部署服务，了解推理加速与成本优化。",
             "resource": {"name": "Docker 官方教程", "url": "https://docs.docker.com/get-started/"}},
            {"id": "aa_eval", "label": "评估与可观测", "dim": "核心技能", "importance": 4,
             "keywords": ["评测", "评估", "evaluation", "benchmark", "ragas", "guardrails", "安全护栏",
                          "langsmith", "tracing", "成本追踪", "可观测", "效果评估", "离线评估", "在线评估",
                          "evaluation", "benchmark", "ragas", "guardrails", "observability",
                          "langsmith", "tracing", "monitoring", "cost tracking",
                          "online evaluation", "offline evaluation", "llm evaluation",
                          "model evaluation", "safety guardrails"],
             "learn": "建立 Agent/RAG 的评测体系（准确率、幻觉率、成本），用 LangSmith 等做链路追踪。",
             "resource": {"name": "RAGAS 评估框架", "url": "https://docs.ragas.io"}},
            {"id": "aa_multi", "label": "多模态能力", "dim": "核心技能", "importance": 3,
             "keywords": ["多模态", "vision", "图像", "语音", "asr", "tts", "whisper", "clip",
                          "文生图", "视频理解", "图像理解", "语音识别",
                          "multimodal", "vision", "image", "speech", "asr", "tts",
                          "whisper", "clip", "image understanding", "speech recognition",
                          "text to image", "video understanding", "audio processing"],
             "learn": "理解多模态模型的接入方式，能为 Agent 增加图像/语音处理能力。",
             "resource": {"name": "OpenAI Vision 文档", "url": "https://platform.openai.com/docs/guides/vision"}},
            {"id": "aa_sec", "label": "AI 安全与护栏", "dim": "核心技能", "importance": 3,
             "keywords": ["安全", "护栏", "guardrail", "越狱", "jailbreak", "内容过滤", "红队", "red team",
                          "提示注入", "prompt injection", "对抗攻击", "安全护栏",
                          "ai safety", "guardrail", "jailbreak", "red team", "prompt injection",
                          "content filtering", "adversarial attack", "security",
                          "llm security", "input validation", "output filtering"],
             "learn": "理解 Agent 的安全风险（提示注入、越狱、数据泄露），能在系统中预埋护栏。",
             "resource": {"name": "OWASP LLM Top 10", "url": "https://owasp.org/www-project-top-10-for-large-language-model-applications/"}},
            {"id": "aa_dataeng", "label": "数据处理/ETL", "dim": "核心技能", "importance": 3,
             "keywords": ["etl", "数据清洗", "爬虫", "数据采集", "向量化", "pipeline",
                          "数据管道", "批处理", "spark", "airflow", "数据预处理",
                          "etl", "data pipeline", "data preprocessing", "data cleaning",
                          "web scraping", "data collection", "batch processing",
                          "spark", "airflow", "data engineering", "data ingestion"],
             "learn": "能构建数据摄入与清洗管线，为 RAG/微调准备高质量语料。",
             "resource": {"name": "Airflow 文档", "url": "https://airflow.apache.org/docs/"}},
            {"id": "aa_test", "label": "测试与工程规范", "dim": "核心技能", "importance": 3,
             "keywords": ["测试", "单元测试", "集成测试", "ci", "cd", "代码规范", "code review",
                          "pytest", "mock", "自动化测试", "回归测试",
                          "testing", "unit test", "integration test", "ci/cd",
                          "code review", "pytest", "mock", "automated testing",
                          "regression test", "software quality", "engineering practice"],
             "learn": "为 Agent 流程写测试（含 mock 模型调用），建立 CI 守门习惯。",
             "resource": {"name": "pytest 文档", "url": "https://docs.pytest.org"}},

            # 项目经验
            {"id": "aa_proj", "label": "Agent 项目经验", "dim": "项目经验", "importance": 5,
             "keywords": ["agent项目", "智能体项目", "搭建agent", "agent开发", "rag系统", "对话系统",
                          "ai应用", "llm应用", "chatbot", "智能客服", "问答系统", "agent落地",
                          "agent project", "agent development", "rag system", "conversational ai",
                          "chatbot", "qa system", "ai application", "llm application",
                          "agent implementation", "intelligent agent", "ai assistant"],
             "learn": "做一个端到端 Agent（如简历优化/客服/数据分析），写清架构与难点。",
             "resource": {"name": "在 GitHub 开源你的 Agent", "url": "https://github.com"}},
            {"id": "aa_full", "label": "全栈交付", "dim": "项目经验", "importance": 4,
             "keywords": ["全栈", "端到端", "完整项目", "前后端", "独立开发",
                          "独立交付", "产品落地", "可演示",
                          "full stack", "end to end", "full stack development",
                          "independent development", "complete project", "full product",
                          "independent delivery", "full cycle", "full ownership"],
             "learn": "独立完成从需求到上线的完整链路，沉淀可演示 Demo。",
             "resource": GENERIC_RESOURCE},
            {"id": "aa_oss", "label": "开源贡献", "dim": "项目经验", "importance": 2,
             "keywords": ["开源", "github", "贡献", "pr", "开源项目",
                          "star", "技术博客", "开源社区",
                          "open source", "github", "contribution", "pull request",
                          "open source project", "tech blog", "oss",
                          "open source community", "contributor"],
             "learn": "给 1-2 个 AI 开源项目提 PR，体现工程协作能力。",
             "resource": {"name": "GitHub Trending", "url": "https://github.com/trending"}},

            # 教育背景
            {"id": "aa_edu", "label": "计算机/AI 相关", "dim": "教育背景", "importance": 3,
             "keywords": ["计算机", "软件", "人工智能", "数据科学", "自动化", "电子信息", "统计",
                          "信息管理", "通信", "数学",
                          "computer science", "software engineering", "ai", "data science",
                          "automation", "electronic engineering", "statistics",
                          "information systems", "telecommunications", "mathematics"],
             "learn": "若非相关背景，可用项目作品集弥补专业相关性。",
             "resource": GENERIC_RESOURCE},
            {"id": "aa_algo", "label": "算法基础", "dim": "教育背景", "importance": 3,
             "keywords": ["算法", "数据结构", "leetcode", "刷题",
                          "动态规划", "图论", "贪心", "二叉树",
                          "algorithm", "data structure", "leetcode", "competitive programming",
                          "dynamic programming", "graph theory", "greedy", "binary tree",
                          "problem solving", "coding interview", "time complexity"],
             "learn": "刷透常见数据结构与算法，应对技术面试笔试。",
             "resource": {"name": "LeetCode", "url": "https://leetcode.cn"}},

            # 综合素养
            {"id": "aa_git", "label": "工程规范", "dim": "综合素养", "importance": 3,
             "keywords": ["git", "测试", "文档", "代码规范", "ci", "单元测试",
                          "commit", "分支管理", "code review", "协作",
                          "git", "version control", "ci/cd", "testing", "documentation",
                          "code quality", "code review", "branch management",
                          "engineering practice", "devops", "software quality"],
             "learn": "养成写测试、写 README、用 Git 协作的工程师习惯。",
             "resource": {"name": "Pro Git 中文", "url": "https://git-scm.com/book/zh/v2"}},
            {"id": "aa_debug", "label": "问题排查", "dim": "综合素养", "importance": 3,
             "keywords": ["调试", "排障", "排查", "定位", "日志", "监控",
                          "可观测", "tracing", "性能分析", "复盘",
                          "debugging", "troubleshooting", "logging", "monitoring",
                          "observability", "tracing", "performance analysis",
                          "root cause analysis", "issue resolution", "debug"],
             "learn": "建立日志/可观测性意识，能系统性定位线上问题。",
             "resource": GENERIC_RESOURCE},
            {"id": "aa_comm", "label": "技术沟通", "dim": "综合素养", "importance": 2,
             "keywords": ["技术文档", "汇报", "讲解", "技术分享", "表达能力",
                          "跨团队沟通", "方案宣讲",
                          "technical writing", "technical communication", "documentation",
                          "tech presentation", "knowledge sharing", "cross team communication",
                          "tech talk", "engineering communication"],
             "learn": "能把技术方案讲给非技术同事听，写好设计文档与复盘。",
             "resource": GENERIC_RESOURCE},
        ],
        "interview_base": [
            "请讲一个你做过的 Agent / RAG 项目，技术栈、架构和你踩过的坑。",
            "如何为 Agent 设计一个带工具调用与失败重试的循环？",
            "RAG 效果不好时，你会从哪些环节排查并优化？",
            "如果大模型 API 超时或幻觉，你的系统如何降级保证体验？",
            "你如何评测一个 Agent 的效果？会关注哪些指标（准确率、幻觉率、成本）？",
        ],
    },

    "ai_ops": {
        "label": "AI 运营",
        "desc": "用 AI 工具提效的内容、用户增长与社群运营能力。",
        "skills": [
            # 核心技能
            {"id": "ao_content", "label": "内容运营", "dim": "核心技能", "importance": 5,
             "keywords": ["内容运营", "内容策划", "文案", "新媒体", "选题", "创作", "公众号", "小红书",
                          "短视频", "抖音", "b站", "视频号", "知乎", "微博", "头条", "seo", "搜索优化", "排版", "封面", "爆款",
                          "content strategy", "content marketing", "copywriting", "social media",
                          "short video", "seo", "content creation", "editorial",
                          "content operations", "content planning", "topic selection"],
             "learn": "建立选题-创作-分发-复盘的内容闭环，沉淀爆款方法论。",
             "resource": {"name": "新榜 / 小红书创作学院", "url": "https://www.newrank.cn"}},
            {"id": "ao_growth", "label": "用户增长", "dim": "核心技能", "importance": 4,
             "keywords": ["用户增长", "增长", "拉新", "留存", "转化", "裂变",
                          "aarrr", "海盗模型", "分销", "邀请", "病毒", "k因子", "触点", "活跃",
                          "user growth", "growth", "user acquisition", "retention", "conversion",
                          "viral growth", "referral", "aarrr", "growth hacking",
                          "user activation", "churn", "growth strategy"],
             "learn": "理解 AARRR 漏斗，能用活动/渠道驱动增长。",
             "resource": {"name": "《增长黑客》", "url": "https://book.douban.com"}},
            {"id": "ao_comm", "label": "社群/私域运营", "dim": "核心技能", "importance": 4,
             "keywords": ["社群", "社区", "私域", "用户运营", "会员", "活跃",
                          "微信群", "企微", "社群运营", "打卡", "ugc", "氛围", "私域流量", "私域运营",
                          "community", "community management", "user engagement",
                          "private domain", "ugc", "member", "user operations",
                          "wechat group", "community operations", "loyalty"],
             "learn": "搭建社群 SOP（拉新-促活-转化），提升留存与活跃。",
             "resource": {"name": "企业微信运营中心", "url": "https://work.weixin.qq.com"}},
            {"id": "ao_data", "label": "数据分析", "dim": "核心技能", "importance": 4,
             "keywords": ["数据分析", "数据看板", "指标", "gmv", "roi", "转化", "留存",
                          "dau", "mau", "转化率", "ctr", "点击率", "完播率", "互动率", "漏斗分析", "bi", "数据透视", "数据驱动",
                          "data analysis", "analytics", "kpi", "gmv", "roi", "conversion",
                          "retention", "ctr", "funnel analysis", "bi", "dashboard",
                          "data driven", "marketing analytics", "performance metrics"],
             "learn": "会用飞书多维表格/BI 看板追踪核心运营指标。",
             "resource": {"name": "飞书多维表格", "url": "https://www.feishu.cn/product/base"}},
            {"id": "ao_act", "label": "活动策划", "dim": "核心技能", "importance": 3,
             "keywords": ["活动策划", "运营活动", "营销活动", "策划", "执行",
                          "sop", "预算", "节奏", "营销", "campaign", "运营方案",
                          "campaign planning", "event planning", "marketing campaign",
                          "campaign execution", "budget management", "sop",
                          "marketing strategy", "campaign management"],
             "learn": "能从目标拆活动方案，控预算与节奏并做复盘。",
             "resource": GENERIC_RESOURCE},
            {"id": "ao_aitool", "label": "AI 工具应用", "dim": "核心技能", "importance": 5,
             "keywords": ["ai工具", "chatgpt", "copilot", "效率工具", "aigc", "文心", "豆包", "kimi", "智能体",
                          "midjourney", "stable diffusion", "剪映", "即梦", "可灵", "suno", "runway", "notion ai", "perplexity", "gemini", "coze", "dify",
                          "ai tools", "chatgpt", "copilot", "productivity", "midjourney",
                          "stable diffusion", "notion ai", "perplexity", "gemini",
                          "ai content", "ai automation", "ai workflow"],
             "learn": "把 AI 用于选题、脚本、图文批量生产，沉淀自己的工作流。",
             "resource": {"name": "AI 工具导航", "url": "https://www.aicollection.com"}},
            {"id": "ao_prompt", "label": "Prompt 工程", "dim": "核心技能", "importance": 3,
             "keywords": ["提示词", "prompt", "提示工程", "ai 写作",
                          "文生图", "文生视频", "批量生成", "ai绘画", "ai写作", "结构化提示",
                          "prompt engineering", "prompt design", "ai writing",
                          "text to image", "text to video", "batch generation",
                          "structured prompt", "ai content generation"],
             "learn": "用结构化提示批量产出稳定质量的运营内容。",
             "resource": {"name": " Prompt 工程指南", "url": "https://www.promptingguide.ai/zh"}},
            {"id": "ao_auto", "label": "自动化工作流", "dim": "核心技能", "importance": 3,
             "keywords": ["自动化", "工作流", "n8n", "zapier", "飞书机器人", "脚本", "批量",
                          "coze", "扣子", "dify", "webhook", "rpa", "api", "流程自动化",
                          "automation", "workflow", "n8n", "zapier", "webhook",
                          "rpa", "workflow automation", "api integration",
                          "process automation", "no code automation"],
             "learn": "用 n8n/飞书机器人把重复运营动作自动化。",
             "resource": {"name": "n8n 官方文档", "url": "https://docs.n8n.io"}},
            {"id": "ao_channel", "label": "渠道投放", "dim": "核心技能", "importance": 3,
             "keywords": ["投放", "广告", "渠道", "sem", "信息流", "买量",
                          "巨量引擎", "腾讯广告", "ocpx", "cpc", "cpm", "roi", "投放优化", "效果广告",
                          "advertising", "sem", "paid media", "cpc", "cpm", "roi",
                          "ad optimization", "performance marketing", "paid acquisition",
                          "social ads", "programmatic", "targeting"],
             "learn": "理解主流投放渠道与 ROI 核算，能小预算跑通测试。",
             "resource": GENERIC_RESOURCE},
            {"id": "ao_user", "label": "用户研究", "dim": "核心技能", "importance": 3,
             "keywords": ["用户调研", "用户画像", "访谈", "问卷", "痛点",
                          "用户分层", "需求洞察", "画像分析", "用户反馈",
                          "user research", "user profile", "user interview", "survey",
                          "user insight", "user feedback", "user segmentation",
                          "customer research", "user need", "pain point"],
             "learn": "建立用户画像与需求分层，指导内容与活动。",
             "resource": GENERIC_RESOURCE},
            {"id": "ao_seo", "label": "AI 搜索 / SEO 优化", "dim": "核心技能", "importance": 3,
             "keywords": ["ai搜索", "geo", "生成引擎优化", "aio", "搜索优化", "seo优化", "内容分发",
                          "搜索流量", "关键词优化", "sem",
                          "seo", "search engine optimization", "geo", "ai search",
                          "generative engine optimization", "content distribution",
                          "keyword optimization", "search traffic", "organic search"],
             "learn": "理解 AI 搜索（如 Perplexity）对传统 SEO 的冲击，优化内容被 AI 收录与引用。",
             "resource": {"name": "Ahrefs SEO 指南", "url": "https://ahrefs.com/blog/zh/what-is-seo/"}},
            {"id": "ao_crm", "label": "用户分层 / CRM", "dim": "核心技能", "importance": 3,
             "keywords": ["crm", "用户分层", "rfm", "生命周期", "忠诚度", "会员体系",
                          "客户管理", "复购", "精细化运营",
                          "crm", "customer relationship management", "rfm",
                          "customer lifecycle", "loyalty", "membership",
                          "customer segmentation", "retention marketing", "cohort"],
             "learn": "用 RFM / 生命周期模型做用户分层与精细化触达。",
             "resource": {"name": "有赞 CRM 学院", "url": "https://www.youzan.com"}},
            {"id": "ao_brand", "label": "品牌 / 公关", "dim": "核心技能", "importance": 2,
             "keywords": ["品牌", "公关", "舆情", "口碑", "品牌传播",
                          "品牌内容", "危机公关", "媒介",
                          "brand", "public relations", "brand communication",
                          "brand awareness", "crisis management", "brand strategy",
                          "pr", "media relations", "reputation management"],
             "learn": "理解品牌建设 basics，能策划品牌内容并处理基础舆情。",
             "resource": GENERIC_RESOURCE},

            # 项目经验
            {"id": "ao_01", "label": "0-1 运营经验", "dim": "项目经验", "importance": 4,
             "keywords": ["从0到1", "0到1", "冷启动", "搭建", "从零", "起号",
                          "账号孵化", "从零到一", "冷启",
                          "0 to 1", "cold start", "build from scratch", "new channel",
                          "greenfield", "account incubation", "starting from zero"],
             "learn": "独立操盘一个账号/社群的冷启动，沉淀增长复盘。",
             "resource": GENERIC_RESOURCE},
            {"id": "ao_ship", "label": "活动落地", "dim": "项目经验", "importance": 4,
             "keywords": ["活动执行", "落地", "复盘", "操盘", "上线",
                          "活动复盘", "项目操盘", "执行落地",
                          "event execution", "campaign delivery", "project delivery",
                          "operation execution", "campaign management", "go live",
                          "campaign launch", "project execution"],
             "learn": "完整跑过一次活动（策划-执行-数据-复盘）。",
             "resource": GENERIC_RESOURCE},
            {"id": "ao_prod", "label": "内容生产", "dim": "项目经验", "importance": 4,
             "keywords": ["内容生产", "选题", "创作", "脚本", "图文", "短视频",
                          "内容产出", "爆款内容", "内容矩阵",
                          "content production", "content creation", "script writing",
                          "short video", "content matrix", "viral content",
                          "content output", "editorial planning"],
             "learn": "产出可量化的内容成果（阅读/涨粉/转化），备好作品集。",
             "resource": GENERIC_RESOURCE},
            {"id": "ao_ecom", "label": "电商 / 直播运营", "dim": "项目经验", "importance": 3,
             "keywords": ["电商", "直播", "带货", "淘宝", "抖音电商", "小红书店铺", "店铺运营",
                          "直播运营", "商品运营", "达人合作", "选品",
                          "ecommerce", "live streaming", "e-commerce", "shop operations",
                          "live commerce", "product management", "influencer collaboration",
                          "taobao", "tiktok shop", "social commerce"],
             "learn": "理解电商/直播的转化链路（种草-进店-下单-复购），能操盘店铺或直播间。",
             "resource": {"name": "抖音电商学习中心", "url": "https://school.jinritemai.com"}},

            # 教育背景
            {"id": "ao_edu", "label": "市场/传媒/商科相关", "dim": "教育背景", "importance": 2,
             "keywords": ["市场营销", "传媒", "新闻", "工商管理", "运营", "广告", "传播",
                          "社会学", "心理学", "公共管理",
                          "marketing", "media", "journalism", "business administration",
                          "advertising", "communications", "sociology", "psychology",
                          "public administration", "business"],
             "learn": "若非相关背景，可用运营作品集证明能力。",
             "resource": GENERIC_RESOURCE},
            {"id": "ao_dataedu", "label": "数据/商科", "dim": "教育背景", "importance": 2,
             "keywords": ["数据", "商科", "经济", "统计", "管理",
                          "应用统计", "商业分析", "市场研究",
                          "data", "business", "economics", "statistics", "management",
                          "applied statistics", "business analysis", "market research",
                          "analytics", "data science"],
             "learn": "补一点数据分析基础，对运营量化很有帮助。",
             "resource": {"name": "可汗学院统计学", "url": "https://zh.khanacademy.org/math/statistics-probability"}},

            # 综合素养
            {"id": "ao_copy", "label": "文案写作", "dim": "综合素养", "importance": 4,
             "keywords": ["写作", "文案", "公众号", "小红书", "标题", "脚本",
                          "钩子", "种草", "带货文案", "小红书文案", "公众号文案", "标题党",
                          "copywriting", "writing", "content writing", "headline",
                          "script writing", "social copy", "marketing copy",
                          "persuasive writing", "storytelling"],
             "learn": "练习不同平台的文案风格，建立标题与钩子方法论。",
             "resource": GENERIC_RESOURCE},
            {"id": "ao_exec", "label": "沟通协调", "dim": "综合素养", "importance": 3,
             "keywords": ["沟通", "协调", "执行", "推进", "跨部门",
                          "项目推进", "资源整合", "落地执行",
                          "communication", "coordination", "execution", "cross team",
                          "resource integration", "project execution", "stakeholder",
                          "operational execution", "teamwork"],
             "learn": "强执行力+跨团队推进，是运营岗的核心软素质。",
             "resource": GENERIC_RESOURCE},
            {"id": "ao_creative", "label": "创意与审美", "dim": "综合素养", "importance": 2,
             "keywords": ["创意", "审美", "策划力", "网感", "热点", "潮流", "内容感觉",
                          "creativity", "aesthetic", "trend awareness", "creative sense",
                          "trend spotting", "content instinct", "creative thinking",
                          "cultural relevance", "popular culture"],
             "learn": "培养网感与热点捕捉能力，提升内容的传播力。",
             "resource": GENERIC_RESOURCE},
        ],
        "interview_base": [
            "请分享一个你从 0 到 1 做起来的账号/社群/活动，关键动作和数据结果是什么？",
            "你如何用 AI 工具把日常运营效率提升一倍？请给具体例子。",
            "如果活动转化不达标，你会从哪些环节做复盘和优化？",
            "请现场为一款 AI 产品写一条面向大学生的小红书推广文案。",
            "当 AI 搜索（如 Perplexity）开始替代传统搜索，你会如何调整内容分发策略？",
        ],
    },
}

# ── 中英文翻译映射 ──────────────────────────────────────
# 用于 matcher.py 的 localize_analysis() 做结果后处理

DIMENSIONS_EN = {
    "核心技能": "Core Skills",
    "项目经验": "Project Experience",
    "教育背景": "Education",
    "综合素养": "Soft Skills",
}

ROLE_LABEL_EN = {
    "AI 产品": "AI Product",
    "AI Agent 开发": "AI Agent Dev",
    "AI 运营": "AI Operations",
}

ROLE_DESC_EN = {
    "面向 AI 产品的需求洞察、LLM 应用认知与 0-1 落地能力。": "Requirement insight, LLM application knowledge, and 0-to-1 delivery for AI products.",
    "面向 LLM / Agent 的工程实现能力：RAG、MCP、多智能体与工程落地。": "Engineering implementation for LLM / Agent: RAG, MCP, multi-agent systems.",
    "用 AI 工具提效的内容、用户增长与社群运营能力。": "Content, user growth and community operations powered by AI tools.",
}

LABEL_EN = {
    # ai_product
    "需求分析": "Requirement Analysis",
    "用户研究": "User Research",
    "PRD 撰写": "PRD Writing",
    "产品原型": "Product Prototyping",
    "数据分析": "Data Analysis",
    "A/B 测试": "A/B Testing",
    "竞品分析": "Competitive Analysis",
    "机器学习基础": "ML Fundamentals",
    "LLM 应用认知": "LLM Application Knowledge",
    "商业化思维": "Business Thinking",
    "AI 原生产品设计": "AI-Native Product Design",
    "Agent 产品认知": "Agent Product Knowledge",
    "AI PM 方法论": "AI PM Methodology",
    "AI 伦理与合规": "AI Ethics & Compliance",
    "产品增长": "Product Growth",
    "0-1 产品经验": "0-to-1 Product Experience",
    "AI 产品落地": "AI Product Delivery",
    "跨团队协作": "Cross-Team Collaboration",
    "项目管理": "Project Management",
    "计算机/相关专业": "CS or Related Major",
    "学历背景": "Education Background",
    "沟通表达": "Communication",
    "逻辑思维": "Logical Thinking",
    "快速学习": "Quick Learning",
    # ai_agent
    "Python": "Python",
    "前端/TS 基础": "Frontend / TypeScript",
    "LangChain/LangGraph": "LangChain / LangGraph",
    "RAG 检索增强": "RAG (Retrieval Augmented)",
    "MCP 协议": "MCP Protocol",
    "大模型 API": "LLM API",
    "向量数据库": "Vector Database",
    "提示工程": "Prompt Engineering",
    "Agent 架构": "Agent Architecture",
    "后端开发": "Backend Development",
    "前端基础": "Frontend Basics",
    "模型微调": "Model Fine-Tuning",
    "部署/推理优化": "Deployment / Inference",
    "评估与可观测": "Evaluation & Observability",
    "多模态能力": "Multimodal",
    "AI 安全与护栏": "AI Safety & Guardrails",
    "数据处理/ETL": "Data Processing / ETL",
    "测试与工程规范": "Testing & Engineering",
    "Agent 项目经验": "Agent Project Experience",
    "全栈交付": "Full-Stack Delivery",
    "开源贡献": "Open Source Contribution",
    "计算机/AI 相关": "CS / AI Related",
    "算法基础": "Algorithm Basics",
    "工程规范": "Engineering Standards",
    "问题排查": "Troubleshooting",
    "技术沟通": "Technical Communication",
    # ai_ops
    "内容运营": "Content Operations",
    "用户增长": "User Growth",
    "社群/私域运营": "Community / Private Domain",
    "活动策划": "Campaign Planning",
    "AI 工具应用": "AI Tools",
    "Prompt 工程": "Prompt Engineering",
    "自动化工作流": "Workflow Automation",
    "渠道投放": "Channel Advertising",
    "用户研究": "User Research",
    "AI 搜索 / SEO 优化": "AI Search / SEO",
    "用户分层 / CRM": "User Segmentation / CRM",
    "品牌 / 公关": "Brand / PR",
    "0-1 运营经验": "0-to-1 Operations",
    "活动落地": "Campaign Delivery",
    "内容生产": "Content Production",
    "电商 / 直播运营": "E-commerce / Live Streaming",
    "市场/传媒/商科相关": "Marketing / Media / Business",
    "数据/商科": "Data / Business",
    "文案写作": "Copywriting",
    "沟通协调": "Coordination",
    "创意与审美": "Creativity & Aesthetic",
}

LEARN_EN = {
    # ai_product
    "练习把模糊诉求拆成可验证的用户故事与验收标准，建立 MRD/PRD 思维。": "Practice breaking vague requests into verifiable user stories and acceptance criteria. Build MRD/PRD thinking.",
    "掌握访谈提纲设计、定性+定量结合的研究方法，建立用户同理心。": "Master interview guide design, qualitative & quantitative research methods. Build user empathy.",
    "用结构化模板写 PRD：背景、目标、范围、功能列表、交互、数据埋点。": "Write PRDs with structured templates: background, goals, scope, feature list, interactions, data tracking.",
    "熟练 Figma 画出可点击原型，能和技术对齐交互细节。": "Use Figma to create clickable prototypes. Align interaction details with engineering.",
    "会用 SQL/神策/GA 看核心指标，用数据驱动迭代决策。": "Use SQL, sensors, GA to track key metrics. Drive iteration decisions with data.",
    "理解实验设计的基本统计原理（显著性、样本量）。": "Understand experiment design basics: statistical significance, sample size.",
    "建立竞品矩阵分析法（功能/体验/商业模式三维度）。": "Build a competitive matrix across features, UX, and business model.",
    "理解监督/无监督、训练/推理、常见模型能力边界，能和算法同学对话。": "Understand supervised/unsupervised learning, training/inference, model capabilities. Talk effectively with ML engineers.",
    "亲自用过主流大模型与 Agent 产品，理解 RAG/Agent/微调的适用边界与产品形态。": "Use mainstream LLMs and Agent products firsthand. Understand RAG, Agent, fine-tuning boundaries.",
    "能设计定价/增长模型，理解 PMF 与单位经济。": "Design pricing & growth models. Understand PMF and unit economics.",
    "理解 AI 原生应用与传统软件的本质差异：从「用户操作」到「用户描述意图、AI 执行」，设计人机协作闭环。": "Understand AI-native vs traditional software: from user operation to intent-driven AI execution.",
    "理解 Agent 能解决什么、不能解决什么，能把业务流程拆成「可自主执行的任务 + 人工确认节点」。": "Understand what Agent can and cannot do. Break workflows into autonomous tasks + human review.",
    "建立 AI 产品特有的方法论：模型能力评估、效果兜底、成本控制、安全边界设计。": "Build AI-specific PM methodology: model eval, fallback, cost control, safety design.",
    "了解生成式 AI 的合规红线（内容安全、版权、个人信息保护），能在产品设计中预埋护栏。": "Understand GenAI compliance boundaries: content safety, copyright, data protection.",
    "理解 AARRR 增长漏斗，能结合产品特性设计激活与留存机制。": "Understand AARRR funnel. Design activation and retention mechanics for your product.",
    "争取独立负责一个小功能或副业项目的从 0 到 1，沉淀复盘文档。": "Own a small feature or side project from 0 to 1. Document the process.",
    "跑通过需求→开发→灰度→上线的完整闭环，准备项目复盘稿。": "Complete a full cycle from requirements → dev → canary → launch. Prepare a retrospective.",
    "练习用 OKR/周会机制推动设计、研发、算法协同。": "Use OKRs and weekly syncs to drive cross-team alignment.",
    "掌握看板/里程碑管理，能控进度与风险。": "Use Kanban and milestone management to control progress and risk.",
    "若非相关背景，可补 1 门产品/数据分析入门课增强说服力。": "If not a relevant major, take an intro course in product or data analysis.",
    "学历为加分项，重点仍应放在项目与作品集。": "Education is a plus. Focus on projects and portfolio.",
    "练习结构化表达（结论先行），沉淀 1 份产品汇报 PPT。": "Practice structured communication. Prepare a product presentation deck.",
    "用 MECE / 金字塔原理组织分析与汇报。": "Use MECE and the Pyramid Principle for analysis and presentations.",
    "建立知识管理习惯（笔记/卡片盒），持续追踪 AI 新动态。": "Build a knowledge management habit. Stay current with AI trends.",
    # ai_agent
    "扎实的 Python 基础（异步、类型注解、虚拟环境、包管理）。": "Solid Python fundamentals: async, type hints, virtual environments, package management.",
    "能用 TS 写简单前端或后端，便于做 Agent 的可视化与联调。": "Write simple frontend or backend in TypeScript for Agent visualization and debugging.",
    "用 LangGraph 编排有状态的多步 Agent 工作流。": "Orchestrate stateful multi-step Agent workflows with LangGraph.",
    "掌握切分/向量化/重排/引用溯源的完整 RAG 链路与评测。": "Master the full RAG pipeline: chunking, embedding, reranking, citation tracing.",
    "理解 MCP 客户端/服务端模型，能为 Agent 封装工具服务。": "Understand MCP client/server model. Wrap tool services for Agents.",
    "熟练调用主流大模型 API，掌握流式输出、重试、降级与成本控制。": "Call mainstream LLM APIs fluently. Handle streaming, retry, fallback, cost control.",
    "选型并落地一种向量库，理解索引与相似度度量。": "Select and deploy a vector database. Understand indexing and similarity search.",
    "掌握角色/约束/示例/思维链等提示技巧与系统提示设计。": "Master role, constraint, few-shot, CoT prompting and system prompt design.",
    "理解规划-执行-反思循环，能设计单/多 Agent 协作架构。": "Understand plan-execute-reflect loops. Design single and multi-agent architectures.",
    "用 FastAPI 构建稳定的 Agent 服务与 API。": "Build stable Agent services and APIs with FastAPI.",
    "能用 Vue/React 做简单交互页，便于联调 Agent 界面。": "Build simple UIs with Vue/React for Agent debugging and demos.",
    "理解 SFT/LoRA 流程与适用场景，知道何时该微调而非提示。": "Understand SFT/LoRA pipelines. Know when to fine-tune vs prompt.",
    "会用 Docker 部署服务，了解推理加速与成本优化。": "Deploy services with Docker. Understand inference acceleration and cost optimization.",
    "建立 Agent/RAG 的评测体系（准确率、幻觉率、成本），用 LangSmith 等做链路追踪。": "Build eval systems: accuracy, hallucination rate, cost. Use LangSmith for tracing.",
    "理解多模态模型的接入方式，能为 Agent 增加图像/语音处理能力。": "Integrate multimodal models. Add image and speech capabilities to Agents.",
    "理解 Agent 的安全风险（提示注入、越狱、数据泄露），能在系统中预埋护栏。": "Understand Agent security risks: prompt injection, jailbreak, data leakage. Build guardrails.",
    "能构建数据摄入与清洗管线，为 RAG/微调准备高质量语料。": "Build data ingestion and cleaning pipelines for RAG and fine-tuning.",
    "为 Agent 流程写测试（含 mock 模型调用），建立 CI 守门习惯。": "Write tests for Agent workflows (with mocked models). Establish CI practices.",
    "做一个端到端 Agent（如简历优化/客服/数据分析），写清架构与难点。": "Build an end-to-end Agent (resume optimizer, customer service, data analysis). Document architecture.",
    "独立完成从需求到上线的完整链路，沉淀可演示 Demo。": "Own full cycle from requirements to launch. Create a demo-ready project.",
    "给 1-2 个 AI 开源项目提 PR，体现工程协作能力。": "Submit PRs to 1-2 AI open-source projects. Demonstrate collaborative engineering.",
    "若非相关背景，可用项目作品集弥补专业相关性。": "If not a CS/AI major, offset with strong project portfolio.",
    "刷透常见数据结构与算法，应对技术面试笔试。": "Master common data structures and algorithms for technical interviews.",
    "养成写测试、写 README、用 Git 协作的工程师习惯。": "Build habits: write tests, write READMEs, collaborate via Git.",
    "建立日志/可观测性意识，能系统性定位线上问题。": "Build logging and observability awareness. Systematically debug production issues.",
    "能把技术方案讲给非技术同事听，写好设计文档与复盘。": "Explain technical solutions to non-technical peers. Write design docs and postmortems.",
    # ai_ops
    "建立选题-创作-分发-复盘的内容闭环，沉淀爆款方法论。": "Build a content loop: topic → creation → distribution → review. Develop viral methodologies.",
    "理解 AARRR 漏斗，能用活动/渠道驱动增长。": "Understand the AARRR funnel. Drive growth through campaigns and channels.",
    "搭建社群 SOP（拉新-促活-转化），提升留存与活跃。": "Build community SOPs for acquisition, activation, and conversion.",
    "会用飞书多维表格/BI 看板追踪核心运营指标。": "Use BI dashboards and spreadsheets to track core operational metrics.",
    "能从目标拆活动方案，控预算与节奏并做复盘。": "Derive campaign plans from goals. Control budget, pacing, and retrospectives.",
    "把 AI 用于选题、脚本、图文批量生产，沉淀自己的工作流。": "Use AI for topic selection, scripting, and batch content production.",
    "用结构化提示批量产出稳定质量的运营内容。": "Use structured prompts for consistent batch content output.",
    "用 n8n/飞书机器人把重复运营动作自动化。": "Automate repetitive operations with n8n or bot tools.",
    "理解主流投放渠道与 ROI 核算，能小预算跑通测试。": "Understand major ad channels and ROI calculation. Run small-budget tests.",
    "建立用户画像与需求分层，指导内容与活动。": "Build user personas and need segmentation to guide content and campaigns.",
    "理解 AI 搜索（如 Perplexity）对传统 SEO 的冲击，优化内容被 AI 收录与引用。": "Understand how AI search impacts SEO. Optimize content for AI indexing.",
    "用 RFM / 生命周期模型做用户分层与精细化触达。": "Use RFM and lifecycle models for user segmentation and targeted outreach.",
    "理解品牌建设 basics，能策划品牌内容并处理基础舆情。": "Understand brand building basics. Create brand content and handle PR.",
    "独立操盘一个账号/社群的冷启动，沉淀增长复盘。": "Independently run a cold-start for an account or community.",
    "完整跑过一次活动（策划-执行-数据-复盘）。": "Run a complete campaign cycle: plan → execute → measure → review.",
    "产出可量化的内容成果（阅读/涨粉/转化），备好作品集。": "Produce measurable content results: reads, followers, conversions.",
    "理解电商/直播的转化链路（种草-进店-下单-复购），能操盘店铺或直播间。": "Understand e-commerce and live streaming conversion funnels.",
    "若非相关背景，可用运营作品集证明能力。": "If not a marketing major, prove capability with operational portfolio.",
    "补一点数据分析基础，对运营量化很有帮助。": "Build foundational data analysis skills for quantitative operations.",
    "练习不同平台的文案风格，建立标题与钩子方法论。": "Practice copywriting across platforms. Build headline and hook methods.",
    "强执行力+跨团队推进，是运营岗的核心软素质。": "Strong execution and cross-team coordination are core operations skills.",
    "培养网感与热点捕捉能力，提升内容的传播力。": "Develop trend awareness and content instinct for viral potential.",
}

# 英文面试问题
INTERVIEW_BASE_EN = {
    "ai_product": [
        "Describe a product project you're most proud of in 3 minutes. What was your role?",
        "If you were to build an AI learning assistant for college students from scratch, how would you start?",
        "How would you decide between RAG and fine-tuning for an AI feature? Explain from a product perspective.",
        "Give an example of how you used data to drive a product iteration.",
        "If an AI feature has only 80% accuracy, how would you design the product to ensure a good user experience?",
    ],
    "ai_agent": [
        "Walk through an Agent or RAG project you built: tech stack, architecture, and challenges.",
        "How would you design an Agent loop with tool calling and failure retry?",
        "If RAG performance is poor, how would you diagnose and optimize?",
        "How does your system degrade gracefully when the LLM API times out or hallucinates?",
        "How do you evaluate an Agent's performance? What metrics matter most?",
    ],
    "ai_ops": [
        "Share an account, community, or campaign you built from 0 to 1. Key actions and results?",
        "How have you used AI tools to double your daily operations efficiency? Give specific examples.",
        "If campaign conversion is below target, how would you diagnose and optimize?",
        "Write a Douyin-style promotional copy for an AI product targeting college students.",
        "As AI search (e.g. Perplexity) replaces traditional search, how would you adjust your content distribution strategy?",
    ],
}


def auto_detect_role(text: str) -> str:
    """根据 JD 文本粗略判断最匹配的岗位。"""
    t = (text or "").lower()
    scores = {}
    for rid, spec in ROLES.items():
        s = 0
        for sk in spec["skills"]:
            s += sum(1 for k in sk["keywords"] if k.lower() in t)
        scores[rid] = s
    best = max(scores, key=scores.get)
    # 若完全无命中，回退到 ai_product
    return best if scores[best] > 0 else "ai_product"
